CONFIG_MAIN_STACK_SIZE=6000
CONFIG_HEAP_MEM_POOL_SIZE=8192

# RPC Configs

# C++ Language Support
CONFIG_CPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_GLIBCXX_LIBCPP=y

# eRPC
CONFIG_ERPC=y
CONFIG_ERPC_TRANSPORT_RPMSG_LITE=y

# RPMSG Lite
CONFIG_IPM=y
CONFIG_EVENTS=y
CONFIG_PRINTK=y
CONFIG_RPMSGLITE=y
CONFIG_RPMSGLITE_QUEUE=y
CONFIG_RPMSGLITE_NS=y
CONFIG_TIMESLICE_SIZE=1
