/*
 * Copyright (c) 2019 Linaro Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/kernel.h>
#include <zephyr/device.h>

#include <zephyr/drivers/display.h>
#include <zephyr/drivers/video.h>

#define LOG_LEVEL CONFIG_LOG_DEFAULT_LEVEL
#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(main);

#include <math.h>

#define VIDEO_DEV_SW "VIDEO_SW_GENERATOR"

#define THRESHOLD 10.0
typedef struct {
    double L;
    double a;
    double b;
} LABColor;

void rgb_to_xyz(uint8_t r, uint8_t g, uint8_t b, double *x, double *y, double *z) {
    double r_lin = r / 255.0;
    double g_lin = g / 255.0;
    double b_lin = b / 255.0;

    r_lin = r_lin > 0.04045 ? pow((r_lin + 0.055) / 1.055, 2.4) : r_lin / 12.92;
    g_lin = g_lin > 0.04045 ? pow((g_lin + 0.055) / 1.055, 2.4) : g_lin / 12.92;
    b_lin = b_lin > 0.04045 ? pow((b_lin + 0.055) / 1.055, 2.4) : b_lin / 12.92;

    *x = r_lin * 0.4124564 + g_lin * 0.3575761 + b_lin * 0.1804375;
    *y = r_lin * 0.2126729 + g_lin * 0.7151522 + b_lin * 0.0721750;
    *z = r_lin * 0.0193339 + g_lin * 0.1191920 + b_lin * 0.9503041;
}

void xyz_to_lab(double x, double y, double z, LABColor *lab) {
    double x_ref = 0.95047;
    double y_ref = 1.00000;
    double z_ref = 1.08883;

    x /= x_ref;
    y /= y_ref;
    z /= z_ref;

    x = x > 0.008856 ? pow(x, 1.0 / 3.0) : (7.787 * x) + (16.0 / 116.0);
    y = y > 0.008856 ? pow(y, 1.0 / 3.0) : (7.787 * y) + (16.0 / 116.0);
    z = z > 0.008856 ? pow(z, 1.0 / 3.0) : (7.787 * z) + (16.0 / 116.0);

    lab->L = (116.0 * y) - 16.0;
    lab->a = 500.0 * (x - y);
    lab->b = 200.0 * (y - z);
}

double cie76_deltaE(LABColor lab1, LABColor lab2) {
    return sqrt(pow(lab1.L - lab2.L, 2) + pow(lab1.a - lab2.a, 2) + pow(lab1.b - lab2.b, 2));
}

void rgb_to_lab(uint32_t color, LABColor *lab) {
    uint8_t r = (color >> 16) & 0xFF;
    uint8_t g = (color >> 8) & 0xFF;
    uint8_t b = color & 0xFF;

    double x, y, z;
    rgb_to_xyz(r, g, b, &x, &y, &z);
    xyz_to_lab(x, y, z, lab);
}

bool is_color_close(uint32_t color1, uint32_t color2, double *dist) {
    LABColor lab1, lab2;

    rgb_to_lab(color1, &lab1);
    rgb_to_lab(color2, &lab2);
	*dist = cie76_deltaE(lab1, lab2);

    return (*dist < THRESHOLD);
}

/*
 * {White, Yellow, Aqua, Green, Purple, Red, Blue, Black}
 * These values are taken from middle of each bar on a real 8-color bar
 * image generated by an ov5640 camera attached to an i.MX RT1170 EVK
 */
static uint32_t xrgb32_colorbar_value[] = {0x00FFFFFF, 0x00FFFF30, 0x0030FFE0, 0x0020FF00,
				    0x00E000FF, 0x00D00020, 0x000000CF, 0x00000700};

// static uint32_t xrgb32_colorbar_value[] = {0xFFFFFFFF, 0xFFFFFF00, 0xFF00FFFF, 0xFF00FF00,
// 				    0xFFFF00FF, 0xFFFF0000, 0xFF0000FF, 0xFF000000};

static bool check_color_bar(const struct video_buffer * const vbuf, int width, int height, uint32_t pixelformat, bool vflip)
{
	uint32_t *pixel;
	int color_idx;
	int bw = width / 8;
	int h, w, i = 0;
	double dist;

	if (pixelformat != VIDEO_PIX_FMT_XRGB32) {
		LOG_ERR("Format %d is currently not supported for this test", pixelformat);
		return false;
	}

	for (h = 0; h < height; h++) {
		for (w = 0; w < width; w++) {
			color_idx = vflip ? 7 - w / bw : w / bw;
			/* Due to performance issue, for each row, check only the pixel in the middle of the color bar */
			if (w == (bw * color_idx + bw / 2)) {
				pixel = (uint32_t *)&vbuf->buffer[i];
				if (!is_color_close(*pixel, xrgb32_colorbar_value[color_idx], &dist)) {
					printk("dist = %f\n", dist); // Test only
					return false;
				}
			}
			i += 4;
		}
	}

	return true;
}

#if DT_HAS_CHOSEN(zephyr_display)
static inline int display_setup(const struct device *const display_dev, const uint32_t pixfmt)
{
	struct display_capabilities capabilities;
	int ret = 0;

	if (!device_is_ready(display_dev)) {
		LOG_ERR("Device %s not found", display_dev->name);
		return -ENODEV;
	}

	printk("\nDisplay device: %s\n", display_dev->name);

	display_get_capabilities(display_dev, &capabilities);

	printk("- Capabilities:\n");
	printk("  x_resolution = %u, y_resolution = %u, supported_pixel_formats = %u\n"
	       "  current_pixel_format = %u, current_orientation = %u\n\n",
	       capabilities.x_resolution, capabilities.y_resolution,
	       capabilities.supported_pixel_formats, capabilities.current_pixel_format,
	       capabilities.current_orientation);

	/* Set display pixel format to match the one in use by the camera */
	switch (pixfmt) {
	case VIDEO_PIX_FMT_RGB565:
		ret = display_set_pixel_format(display_dev, PIXEL_FORMAT_BGR_565);
		break;
	case VIDEO_PIX_FMT_XRGB32:
		ret = display_set_pixel_format(display_dev, PIXEL_FORMAT_ARGB_8888);
		break;
	default:
		return -ENOTSUP;
	}

	if (ret) {
		LOG_ERR("Unable to set display format");
		return ret;
	}

	return display_blanking_off(display_dev);
}

static inline void video_display_frame(const struct device *const display_dev,
				       const struct video_buffer *const vbuf,
				       const struct video_format fmt)
{
	struct display_buffer_descriptor buf_desc;

	buf_desc.buf_size = vbuf->bytesused;
	buf_desc.width = fmt.width;
	buf_desc.pitch = buf_desc.width;
	buf_desc.height = fmt.height;

	display_write(display_dev, 0, 0, &buf_desc, vbuf->buffer);
}
#endif

int main(void)
{
	struct video_buffer *buffers[CONFIG_VIDEO_BUFFER_POOL_NUM_MAX], *vbuf;
	struct video_format fmt;
	struct video_caps caps;
	struct video_frmival frmival;
	struct video_frmival_enum fie;
	unsigned int frame = 0;
	size_t bsize;
	int i = 0;
	int err;

#if DT_HAS_CHOSEN(zephyr_camera)
	const struct device *const video_dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_camera));

	if (!device_is_ready(video_dev)) {
		LOG_ERR("%s: video device is not ready", video_dev->name);
		return 0;
	}
#else
	const struct device *const video_dev = device_get_binding(VIDEO_DEV_SW);

	if (video_dev == NULL) {
		LOG_ERR("%s: video device not found or failed to initialized", VIDEO_DEV_SW);
		return 0;
	}
#endif

	printk("Video device: %s\n", video_dev->name);

	/* Get capabilities */
	if (video_get_caps(video_dev, VIDEO_EP_OUT, &caps)) {
		LOG_ERR("Unable to retrieve video capabilities");
		return 0;
	}

	printk("- Capabilities:\n");
	while (caps.format_caps[i].pixelformat) {
		const struct video_format_cap *fcap = &caps.format_caps[i];
		/* fourcc to string */
		printk("  %c%c%c%c width [%u; %u; %u] height [%u; %u; %u]\n",
		       (char)fcap->pixelformat, (char)(fcap->pixelformat >> 8),
		       (char)(fcap->pixelformat >> 16), (char)(fcap->pixelformat >> 24),
		       fcap->width_min, fcap->width_max, fcap->width_step, fcap->height_min,
		       fcap->height_max, fcap->height_step);
		i++;
	}

	/* Get default/native format */
	if (video_get_format(video_dev, VIDEO_EP_OUT, &fmt)) {
		LOG_ERR("Unable to retrieve video format");
		return 0;
	}

	printk("- Default format: %c%c%c%c %ux%u\n", (char)fmt.pixelformat,
	       (char)(fmt.pixelformat >> 8), (char)(fmt.pixelformat >> 16),
	       (char)(fmt.pixelformat >> 24), fmt.width, fmt.height);

	if (!video_get_frmival(video_dev, VIDEO_EP_OUT, &frmival)) {
		printk("- Default frame rate : %f fps\n",
		       1.0 * frmival.denominator / frmival.numerator);
	}

	printk("- Supported frame intervals for the default format:\n");
	memset(&fie, 0, sizeof(fie));
	fie.format = &fmt;
	while (video_enum_frmival(video_dev, VIDEO_EP_OUT, &fie) == 0) {
		if (fie.type == VIDEO_FRMIVAL_TYPE_DISCRETE) {
			printk("   %u/%u ", fie.discrete.numerator, fie.discrete.denominator);
		} else {
			printk("   [min = %u/%u; max = %u/%u; step = %u/%u]\n",
			       fie.stepwise.min.numerator, fie.stepwise.min.denominator,
			       fie.stepwise.max.numerator, fie.stepwise.max.denominator,
			       fie.stepwise.step.numerator, fie.stepwise.step.denominator);
		}
		fie.index++;
	}

	video_set_ctrl(video_dev, VIDEO_CID_CAMERA_TEST_PATTERN, (void*)1);

#if DT_HAS_CHOSEN(zephyr_display)
	const struct device *const display_dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_display));

	if (!device_is_ready(display_dev)) {
		LOG_ERR("%s: display device not ready.", display_dev->name);
		return 0;
	}

	err = display_setup(display_dev, fmt.pixelformat);
	if (err) {
		LOG_ERR("Unable to set up display");
		return err;
	}
#endif

	/* Size to allocate for each buffer */
	bsize = fmt.pitch * fmt.height;

	/* Alloc video buffers and enqueue for capture */
	for (i = 0; i < ARRAY_SIZE(buffers); i++) {
		/*
		 * For some hardwares, such as the PxP used on i.MX RT1170 to do image rotation,
		 * buffer alignment is needed in order to achieve the best performance
		 */
		buffers[i] = video_buffer_aligned_alloc(bsize, CONFIG_VIDEO_BUFFER_POOL_ALIGN);
		if (buffers[i] == NULL) {
			LOG_ERR("Unable to alloc video buffer");
			return 0;
		}

		video_enqueue(video_dev, VIDEO_EP_OUT, buffers[i]);
	}

	/* Start video capture */
	if (video_stream_start(video_dev)) {
		LOG_ERR("Unable to start capture (interface)");
		return 0;
	}

	printk("Capture started\n");

	/* Grab video frames */
	while (1) {
		err = video_dequeue(video_dev, VIDEO_EP_OUT, &vbuf, K_FOREVER);
		if (err) {
			LOG_ERR("Unable to dequeue video buf");
			return 0;
		}

		printk("Got frame %u! size: %u; timestamp %u ms\n", frame++, vbuf->bytesused,
		       vbuf->timestamp);

		/* Check color bar pattern content */
		if (check_color_bar(vbuf, fmt.width, fmt.height, fmt.pixelformat, false))
			printk("Pattern OK\n");
		else
			printk("Pattern KO\n");

#if DT_HAS_CHOSEN(zephyr_display)
		video_display_frame(display_dev, vbuf, fmt);
#endif

		err = video_enqueue(video_dev, VIDEO_EP_OUT, vbuf);
		if (err) {
			LOG_ERR("Unable to requeue video buf");
			return 0;
		}
	}
}
