CONFIG_UHC_DRIVER=y
CONFIG_USB_HOST_STACK=y
CONFIG_USBH_HID_BOOT_CLASS=y
CONFIG_USBH_HID_BOOT_INSTANCES_COUNT=1

CONFIG_INPUT=y

CONFIG_LOG=y
CONFIG_USBH_LOG_LEVEL_INF=y
CONFIG_USBH_HID_BOOT_LOG_LEVEL_INF=y
