/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __EMBEDDED_RPC_EXTERNAL_H__
#define __EMBEDDED_RPC_EXTERNAL_H__

#include <zephyr/drivers/video.h>

#include <src/core/mp_pad.h>

/* typedef for @external has to be done manually as it is not automatically generated by erpcgen */
typedef struct video_format video_format;
typedef struct video_format_cap video_format_cap;
typedef enum mp_pad_direction mp_pad_direction;

#endif /* __EMBEDDED_RPC_EXTERNAL_H__ */
