# Network configuration
CONFIG_NETWORKING=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n

# HTTP Server
CONFIG_HTTP_SERVER=y
CONFIG_HTTP_SERVER_MAX_CLIENTS=2
CONFIG_HTTP_SERVER_MAX_STREAMS=2

# JSON Library
CONFIG_JSON_LIBRARY=y

# Logging
CONFIG_LOG=y
